# SPDX-FileCopyrightText: 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0 License

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  getStreams:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: crud/
      Handler: streams.handler
      Runtime: nodejs12.x
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref DynamoDBTable
      Events:
        getStreams:
          Type: Api 
          Properties:
            Path: /videostream/{id}
            Method: any
        allOperations:
          Type: Api 
          Properties:
            Path: /videostream
            Method: post
        allGetOperations:
          Type: Api 
          Properties:
            Path: /videostream
            Method: get

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "video-metadata"
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
#https://a3h9s581y7.execute-api.us-east-1.amazonaws.com/Prod/hello/