# SPDX-FileCopyrightText: 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0 License

version: '2'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
